# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.box = "generic/centos9s"
    config.vm.provider "virtualbox" do |v|
      v.memory = 256
      v.cpus = 1
    end
  
    config.vm.define "crontask" do |crontask|
      repo_client.vm.hostname = "crontask"
      repo_client.vm.provision "shell", path: "mail_sender_cron.sh"
      box.vm.provision "shell", inline: <<-SHELL
      echo @hourly /home/administrator/otus_vm/Lab10/mail_sender_cron.sh flazhka@gmail.com > cronfile
      crontab cronfile

    end
  
  end