---

- name: VPN
  hosts: all
  #gather_facts: no
  become: true
  vars_files:
    - defaults/main.yml

  tasks:
    - name: Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present

    - name: Set timezone to Europe/Moscow
      timezone:
        name: Europe/Moscow
    
    - name: Restart chronyd
      service:
        name: chronyd
        state: restarted
    
    - name: install soft
      yum:
        name: 
          - nano
          - traceroute
          - tcpdump
          - net-tools
          - openvpn
          - iperf3
        state: present

    - name: copy static.key
      template:
        src: static.key
        dest: /etc/openvpn/static.key
        owner: root
        group: root
        mode: 0640

    - name: copy server.conf
      template:
        src: "{{ ansible_hostname }}.conf" 
        dest: /etc/openvpn/server.conf
        owner: root
        group: root
        mode: 0640
      notify:
          - restart ovpn

  handlers:
    - name: restart ovpn
      service:
        name: openvpn@server
        state: restarted
        enabled: true