# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 512
    v.cpus = 1
  end

  config.vm.define "pgsqlmaster" do |pgsqlmaster|
    pgsqlmaster.vm.network "private_network", ip: "192.168.56.30"
    pgsqlmaster.vm.hostname = "pgsqlmaster"
  end

  config.vm.define "pgsqlslave" do |pgsqlslave|
    pgsqlslave.vm.network "private_network", ip: "192.168.56.31"
    pgsqlslave.vm.hostname = "pgsqlslave"

    pgsqlslave.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.become = "true"
      ansible.host_key_checking = "false"
      ansible.limit = "all"
    end

  end
  
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
  SHELL
  
end
