Servers:
  hosts:
    testClient1:
      ansible_host: 192.168.56.12
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/testClient1/virtualbox/private_key  

    testServer1:
      ansible_host: 192.168.56.13
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/testServer1/virtualbox/private_key
    
    testClient2:
      ansible_host: 192.168.56.14
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/testClient2/virtualbox/private_key

    testServer2:
      ansible_host: 192.168.56.15
      ansible_port: 22
      ansible_private_key_file: .vagrant/machines/testServer2/virtualbox/private_key

  children:
    routers:
      hosts:
        inetRouter:
          ansible_host: 192.168.56.10
          ansible_port: 22
          ansible_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key  
        
        centralRouter:
          ansible_host: 192.168.56.11
          ansible_port: 22
          ansible_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key


