# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 512
    v.cpus = 1
  end

  config.vm.define "mysqlmaster" do |mysqlmaster|
    mysqlmaster.vm.network "private_network", ip: "192.168.56.10"
    mysqlmaster.vm.hostname = "mysqlmaster"
  end

  config.vm.define "mysqlslave" do |mysqlslave|
    mysqlslave.vm.network "private_network", ip: "192.168.56.20"
    mysqlslave.vm.hostname = "mysqlslave"

    mysqlslave.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.become = "true"
      ansible.host_key_checking = "false"
      ansible.limit = "all"
    end

  end
  
  config.vm.provision "shell", inline: <<-SHELL
    mkdir -p ~root/.ssh; cp ~vagrant/.ssh/auth* ~root/.ssh
    sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
    systemctl restart sshd
  SHELL
  
end
