# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "generic/centos9s"
  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end

  config.vm.define "web" do |web|
    web.vm.network "private_network", ip: "192.168.50.10"
    web.vm.hostname = "web"
  end

  config.vm.define "log" do |log|
    log.vm.network "private_network", ip: "192.168.50.11"
    log.vm.hostname = "log"
  end

end