# -*- mode: ruby -*-
# vim: set ft=ruby :
disk_controller = 'IDE'

MACHINES = {
  :zfs => {
        :box_name => "generic/centos9s",
        :box_version => "4.2.16",
    :disks => {
        :sata1 => {
            :dfile => './sata1.vdi',
            :size => 256,
            :port => 1
        },
        :sata2 => {
            :dfile => './sata2.vdi',
            :size => 256, # Megabytes
            :port => 2
        },
        :sata3 => {
            :dfile => './sata3.vdi',
            :size => 256,
            :port => 3
        },
        :sata4 => {
            :dfile => './sata4.vdi',
            :size => 256, 
            :port => 4
        },
        :sata5 => {
            :dfile => './sata5.vdi',
            :size => 256,
            :port => 5
        },
        :sata6 => {
            :dfile => './sata6.vdi',
            :size => 256,
            :port => 6
        },
        :sata7 => {
            :dfile => './sata7.vdi',
            :size => 256, 
            :port => 7
        },
        :sata8 => {
            :dfile => './sata8.vdi',
            :size => 256, 
            :port => 8
        },
    } 
  },
}

Vagrant.configure("2") do |config|
  MACHINES.each do |boxname, boxconfig|
      config.vm.define boxname do |box|
        box.vm.box = boxconfig[:box_name]
        box.vm.box_version = boxconfig[:box_version]
        box.vm.host_name = "zfs"
        box.vm.provider :virtualbox do |vb|
              vb.customize ["modifyvm", :id, "--memory", "1024"]
              needsController = false
        boxconfig[:disks].each do |dname, dconf|
              unless File.exist?(dconf[:dfile])
              vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
         needsController =  true
         end
        end
            if needsController == true
                vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                boxconfig[:disks].each do |dname, dconf|
                vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                end
             end
          end
        box.vm.provision "shell",
          name: "Setup zfs",
          path: "zsh_install_srv.sh"
        end
      SHELL
    end
  end
end
