#Otus dz2
#--------------------------------------------------------------------------

# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = { #Описываем переменные для создания vm
  :raidconfig => { #Указываем имя ВМ 
    :box_name => "generic/centos9s", #Версия образа ос
    :ip_addr => '192.168.56.101', #IP адрес
    :disks => { #Дополнительные диски в системе
      :sata1 => {
        :dfile => './sata1.vdi', #Где будут расположены
        :size => 100, #Объем в мегабайтах
        :port => 1 #Порт на контроллере
      },
      :sata2 => {
        :dfile => './sata2.vdi',
        :size => 100,
        :port => 2
      },
      :sata3 => {
        :dfile => './sata3.vdi',
        :size => 100,
        :port => 3
      },
      :sata4 => {
        :dfile => './sata4.vdi',
        :size => 100,
        :port => 4
      },
      :sata5 => {
        :dfile => './sata5.vdi',
        :size => 100,
        :port => 5
      }
    }
  },
}

Vagrant.configure("2") do |config| #Циклы создание vm
  MACHINES.each do |boxname, boxconfig| 
      config.vm.define boxname do |box|
          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s
          box.vm.network "private_network", ip: boxconfig[:ip_addr]
          box.vm.provider :virtualbox do |vb|
            vb.customize ["modifyvm", :id, "--memory", "1024"]
            needsController = false
            boxconfig[:disks].each do |dname, dconf|
              unless File.exist?(dconf[:dfile])
                vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                needsController =  true
              end
              end
                  if needsController == true
                     #vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ] #Создание нового контроллера
                     boxconfig[:disks].each do |dname, dconf|
                         vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                     end
                  end
          end
          box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          yum install -y mdadm smartmontools hdparm gdisk #Установка приложений
          mdadm --zero-superblock --force /dev/sd{b,c,d,e,f} #Зануление суперблоков
          mdadm --create --verbose /dev/md0 -l 6 -n 5 /dev/sd{b,c,d,e,f} #Создание RAID5
          SHELL
        end
  end
end