# -*- mode: ruby -*-
# vi: set ft=ruby : vsa
Vagrant.configure(2) do |config|
    config.vm.box = "generic/centos9s"
    config.vm.box_version = "4.2.16"
    config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
  end
   config.vm.define "nfss" do |nfss|
   nfss.vm.network "private_network", ip: "192.168.10.30", virtualbox__intnet: "net1"
   nfss.vm.hostname = "nfss"
  end
   config.vm.define "nfsc" do |nfsc|
   nfsc.vm.network "private_network", ip: "192.168.10.31", virtualbox__intnet: "net1"
   nfsc.vm.hostname = "nfsc"
  end
end  